### ISSUE TITLE
bug: Slider changes don't take effect immediately

### ISSUE THREAD

**Issue by oSumAtrIX** [KTibow/m3-svelte#94] opened 2024-01-20 21:40 UTC
# Issue

Slider changes don't take effect immediately. This is reproducible on a clean Chrome profile. I have seen similar issues on different pages. I believe the issue may be caused by blocking the render thread. This could be solved by rendering every render tick using https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame. 

https://github.com/KTibow/m3-svelte/assets/13122796/be6d5f9a-0fc0-4a05-a0f8-8f9e08628efe

# Reference

![image](https://github.com/KTibow/m3-svelte/assets/13122796/de7e8ee3-f82e-46f2-8463-308532b6749c)
ref: https://m3.material.io/components/sliders/guidelines

**Comment by KTibow** [comment] 2024-01-20 21:43
The slider is controlled with a hidden `<input>` and displayed with a tweened input. I can't reproduce this issue in Chromium.
[Screencast from 2024-01-20 13-43-31.webm](https://github.com/KTibow/m3-svelte/assets/10727862/479e9484-25e5-438b-a2a0-75808330e8a1)

**Comment by KTibow** [comment] 2024-01-21 02:15
To be clear, "take effect immediately" just means that the value of sliders should be immediately reflected. This is up to the user of the component to handle.

**Comment by oSumAtrIX** [comment] 2024-01-21 02:37
In the reference you can see the slider not lagging behind, whereas in your component it does. I have seen this exact behavior in places where mouse.input was not correctly handled, so this can't possibly be intended

**Comment by KTibow** [comment] 2024-01-21 02:43
I believe the issue is that your browser isn't properly sending the `input` event. I tested with Chromium and Firefox and these browsers send inputs every 20 or 10 milliseconds, but if your browser is less frequent (as I've seen on Chrome Mobile when the touch isn't staying on the slider) it will get tweened in between. The alternative, if I removed the tweening, is it teleporting between states

**Comment by oSumAtrIX** [comment] 2024-01-25 17:54
I am unsure, as I've reproduced this issue on a clean Chrome installation. I can register events at any mouse movement input.

**Comment by KTibow** [comment] 2024-02-25 22:52
I'm planning to close this as a. this doesn't affect most users b. this isn't my fault c. i can't fix this

**Comment by oSumAtrIX** [comment] 2024-02-25 22:55
In the PR description I have outlined the issue and suggested a solution. Instead of rendering each value change, you only render each frame. The mouse reports for example thousand events a second, but you only need 60. The function i sent above does exactly that. Your mouse event handler is used to update the value 1000 times a second whereas the bar is rendered 60 times a second. I am pretty sure this will solve the issue

**Comment by oSumAtrIX** [comment] 2024-02-25 22:56
I also suspect, that a higher report rate will cause more jank as outlined. I believe on mice where the report rate is 250, such as on touchpads or office mice, this issue is seen less prominent, because well, its just 250 renders

**Comment by oSumAtrIX** [comment] 2024-02-25 22:58
Update: I am reproducing the same issue on my iPad. 1000 reports per second as well.

**Comment by KTibow** [comment] 2024-02-25 23:00
That's an interesting claim, but it's unsubstantiated and if there was a fix it would ought to be at the svelte level (I'm just using their `tweened` store).

**Comment by oSumAtrIX** [comment] 2024-02-25 23:00
Update 2: The issue is reproducible on my Pixel 7 Pro, using Chrome as well as Firefox

**Comment by oSumAtrIX** [comment] 2024-02-25 23:02
I suggest you to create a minimal replicable environment as well as with my solution. Like I said, the issue occurs on every of my device, iOS, Android, Windows, Chrome and Firefox, clean profiles, showing the issue is widespread. If you render once per frame, instead of 6 times more, the issue should not occur anymore.

**Comment by oSumAtrIX** [comment] 2024-02-25 23:06
The issue seems to not occur on here: https://material-web.dev/components/slider/stories/

**Comment by KTibow** [comment] 2024-02-25 23:14
Since I can't repro this I'm going to ask you to. Tell me what happens when you try dragging each of the red bars on https://svelte.dev/repl/89837a0c7e55406e81b3409655e2e2fa?version=4.2.12.

**Comment by oSumAtrIX** [comment] 2024-02-25 23:18
https://github.com/KTibow/m3-svelte/assets/13122796/787397ea-a57e-42d2-b40d-3221ebaea2f0

Notice how the slider easing is smooth compared to the issue I am reporting?

**Comment by KTibow** [comment] 2024-02-25 23:24
If I understand correctly, you couldn't reproduce those issues with the repro I sent. In that case I honestly don't know what to do, since the two environments are as similar as possible. The only last thing I could try is using the original easing.

**Comment by oSumAtrIX** [comment] 2024-02-25 23:29
You render each event. In my original recording in the PR description you can see that once I stop filling the input buffer with inputs, the renderer immediately catches up, whereas when I constantly move my cursor, you can see that rendering slows down. The issue is not reproducible on your link nor on M3 webs official demo and I believe it will be solved once you fix the performance issue by rendering only once per frame

**Comment by KTibow** [comment] 2024-02-25 23:37
But due to how the code works, there should be absolutely no reason for there to be a difference between my minimal repro and the actual component, at least for frame-related reasons.

(FYI there is no "render" here, it's just Svelte's own stores and ticks and stuff, if there was a place to throttle it it would be at the input to the store)

**Comment by oSumAtrIX** [comment] 2024-02-25 23:40
The issue I am referring to has nothing to do with Svelte or your implementation per se. I have seen this issue on a couple pages that have rendered every single events. The issue is most definitely solveable by rendering once per frame. I am not sure where the difference is between your link and your m3 site and the official m3 site thought, but if they all render every single event, you compromise performance as experienced in my case. Can you reproduce on your phone?

**Comment by KTibow** [comment] 2024-02-25 23:48
On my phone, everything works perfectly as long as I keep my finger on the slider. If I move it off, it seems Chrome decreases the interval that it sends the events at (not something I can do anything about).

(Phone: OP 7 pro, android 12, 90hz refresh rate)

**Comment by oSumAtrIX** [comment] 2024-02-25 23:50
The intervals are not changed. An event is sent every time your mouse reports one. What suffers is overflowing the renderer with events which is solved using the original solution

**Comment by KTibow** [comment] 2024-02-25 23:52
Okay, notably the issue seems very bad when I'm using the repl I sent, but it gets better if I change the easing back to default. Seems like I might be able to solve this by throttling the inputs to the store.

> the renderer

Which renderer are you referring to?

**Comment by oSumAtrIX** [comment] 2024-02-25 23:53
Whatever draws on the screen. The renderer is called if you for example change the width of a div

**Comment by KTibow** [comment] 2024-02-26 00:00
Ah - no, that's not a problem. The renderer only checks the new data every frame. Heck, Svelte internally uses `loop` to update the result of the store, using `requestAnimationFrame` under the hood!

The real problem is that I was using the wrong type of store. `tweened` is for discrete updates, but I should've been using `spring`, which can accept live influxes of values. I'll see if I can fix this soon.

**Closed** 2024-04-25 14:11 UTC
